[package]
name = "aws_sig_verify"
version = "0.2.0"
authors = ["David Cuthbert <dacut@kanga.org>"]
description = "AWS SigV4 signature verification"
keywords = ["AWS", "Amazon"]
homepage = "https://github.com/dacut/rust-aws-sig"
repository = "https://github.com/dacut/rust-aws-sig"
license = "Apache-2.0"
edition = "2018"
exclude = ["tests/*"]

[lib]
name = "aws_sig_verify"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "^0.4"
hex = "^0.4"
lazy_static = "^1.4.0"
regex = "^1.3"
ring = "^0.16"