[package]
name = "aws_sig_verify"
version = "0.8.0"
authors = ["David Cuthbert <dacut@kanga.org>"]
description = "AWS SigV4 signature verification"
keywords = ["AWS", "Amazon"]
homepage = "https://github.com/dacut/rust-aws-sig"
repository = "https://github.com/dacut/rust-aws-sig"
license = "Apache-2.0"
edition = "2018"
exclude = ["tests/*"]
readme = "README.md"

[lib]
name = "aws_sig_verify"

[dependencies]
async-trait = "^0.1"
chrono = "^0.4"
hex = "^0.4"
http = "^0.2"
lazy_static = "^1.4.0"
log = "^0.4"
regex = "^1.3"
ring = "^0.16"
serde = { version = "^1.0", features = [ "derive" ] }
serde_derive = "^1.0"

[dev-dependencies]
env_logger = "^0.8"
tokio = { version = "^1.4", features = [ "macros", "rt" ] }
test-env-log = "0.2"